#!/bin/bash
#
# Jared Moskowitz
# convertToARFF9
#
# Converts ALL data files of 9 features in a directory to .arff files
# if the files being converted end in .txt

export CLASSPATH=/opt/shared/weka/weka-3-6-10/weka.jar:$CLASSPATH
export WEKADATA=/opt/shared/weka/weka-3-6-10/data

for f in *.txt; do

        FILE1=$f
        sed 's/.$//' $FILE1 > remp.csv
        sed "s/\s/,/g" remp.csv > higgs.csv
        echo "MET,MET_phi,leadingLep_E,leadingLep_px,leadingLep_pz,subleadingLep_E,subleadingLep_px,subleadingLep_py,subleadingLep_pz,FW1,FW2,FW3,FW4,FW5,jet_et_total,jet_energy_total,jet_px,jet_py,jet_pz,HT,EV2,EV1,mll,mjj,met-phi_centrality,mt,DYjj,sumMlj,dphill,contOLV,ptTotal,class" | cat - higgs.csv > temp && mv temp higgs.csv

        NEWFILE="${f%.txt}.arff"
        java -cp /opt/shared/weka/weka-3-6-10/weka.jar weka.core.converters.CSVLoader higgs.csv > $NEWFILE
        sed -i '34s/.*/@attribute label {-1, 1}/' $NEWFILE
done

#rm higgs.csv
#rm remp.csv
